name: Docker Image CI

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]
    workflow_dispatch:
        inputs:
            tags:
                description: 'Manual Build'
                required: false

jobs:
    build-and-push:
        runs-on: ubuntu-latest

        env:
            IMAGE_NAME: python_github_calendar_api
        
        steps:
        -
            name: Checkout Code
            uses: actions/checkout@v4
        
        -
            name: Set up QEMU
            uses: docker/setup-qemu-action@v3
        
        -
            name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
        
        -
            name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
                username: ${{ secrets.DOCKER_HUB_USERNAME }}
                password: ${{ secrets.DOCKER_HUB_TOKEN }}
        
        -
            name: Get current datetime for Image Tag
            id: datetime
            run: echo "::set-output name=tag::$(TZ='Asia/Shanghai' date +'%Y%m%d_%H%M%S')"
        
        -
            name: Build and Push Image
            uses: docker/build-push-action@v5
            with:
                context: .
                platforms: |
                    linux/386
                    linux/amd64
                    linux/arm/v6
                    linux/arm/v7
                    linux/arm64/v8
                    linux/ppc64le
                    linux/s390x
                push: true
                tags: |
                    ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.datetime.outputs.tag }}
                    ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
